import { useParams } from "react-router-dom";
import useAsync from '../../hooks/useAsync.js';
import { BsStars } from "react-icons/bs";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeHighlight from "rehype-highlight"
import { fetchApi } from '../../utils/fetchApi.js';
import Notice from '../../components/html/Notice.jsx';
import { formatIsoString } from '../../utils/formatIsoString.js';

import LoadingDisplay from '../../components/html/LoadingDisplay.jsx';

import { useEffect, useState } from 'react';

const SurveySummary = () => {
  const { id } = useParams();
  const [summary, setSummary] = useState(null);
  const [survey, setSurvey] = useState(null);
  const [getSummary, { isLoading, error }] = useAsync(async () => {
    const res = await fetchApi("get", `/survey/summarize/${id}`);
    if (!res?.success) return;
    setSurvey(res.survey);
    setSummary(res?.response?.choices[0]?.message?.content);
    console.log(res);
  }, [id]);

  useEffect(() => {
    getSummary();
  }, [id]);
  
  if(isLoading){
    return <div className = "w-full h-96 flex justify-center animate-pulse duration-100 text-lg items-center">
      <div className = "flex gap-2 items-center"><BsStars size = "30" /> Generating a response...</div>
    </div>
  }

  return (
    <div className="max-w-4xl mx-auto p-4">
      {error && (
        <div className="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded mb-6">
          <p className="font-semibold">Error:</p>
          <p>{error}</p>
        </div>
      )}
      {survey && (
        <div className="mb-6 bg-zinc-950">
          <h1 className="text-2xl font-bold ">{survey.title}</h1>
          {survey.description && <p className="text-neutral-100 mb-1">{survey.description}</p>}
          {survey.targetRespondents && <p className="text-neutral-100/80 text-sm">Target: {survey.targetRespondents}</p>}
          {survey.createdAt && <p className="text-neutral-100/50 text-sm">Conducted {formatIsoString(survey.createdAt)}</p>}
        </div>
      )}
      {summary ? (
        <div className="prose max-w-none text-neutral-100 p-3 sm:p-6 bg-zinc-900 rounded-lg shadow-md">
          <div className = "flex flex-col justify-center my-3 items-center">
                      <div className = "w-full flex justify-center items-center gap-2"> 
          <BsStars size = "20" />
          <p>AI Summary</p> 
        
          </div>
          <p className = "text-xs opacity-50">openai/gpt-oss-120b</p>
          </div>
          <div className = "overflow-x-auto">
                      <ReactMarkdown
          rehypePlugins={[rehypeRaw, rehypeHighlight]}
          remarkPlugins={[remarkGfm]}>
            {summary}
          </ReactMarkdown>
          </div>
          <div className = "mt-6 mb-4 text-center ">
            <Notice>
              Note: This summary was generated by AI and may occasionally contain inaccuracies or hallucinated information.

            </Notice>
          </div>
        </div>
      ) : (
        <p className="text-neutral-100 h-20 flex justify-center items-center">No summary available.</p>
      )}
    </div>
  );
};

export default SurveySummary;