import { Card } from "@/components/ui/card";
import api from "@/lib/axios.instance";
import { useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeHighlight from "rehype-highlight";
import LoadingDisplay from "@/components/ui/LoadingDisplay";
import { useAccount } from "../../account/hooks/useAccount";

const SurveySummaryPage = () => {
  const { surveyId } = useParams();
  const { data: user } = useAccount();

  const { data: summary, isPending: isLoading } = useQuery({
    queryFn: async () => {
      const res = await api.get(`/api/assistant/summary/${surveyId}`);
      return res.data.summary;
    },
    queryKey: ["summary", surveyId],
    enabled: !!user && !!surveyId,
  });

  return (
    <div className="max-w-5xl mx-auto space-y-6">
      <div className="bg-white dark:bg-zinc-950 rounded-xl  p-6 space-y-6">
        {isLoading ? (
          <LoadingDisplay />
        ) : summary ? (
          <>
            <div className="flex flex-col justify-center items-center gap-1 pb-4 border-b border-zinc-200 dark:border-zinc-900">
              <div className="flex justify-center items-center gap-2">
                <img
                  src="/star.gif"
                  className="text-blue-600 lg:size-10 dark:text-blue-400"
                />
                <h2 className="text-3xl font-bold tracking-tighter text-zinc-900 dark:text-neutral-100">
                  AI Summary
                </h2>
              </div>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                openai/gpt-oss-120b
              </p>
            </div>

            <Card className="overflow-x-auto bg- px-4 prose max-w-none dark:text-neutral-100 text-zinc-900 rounded-lg">
              <ReactMarkdown
                rehypePlugins={[rehypeRaw, rehypeHighlight]}
                remarkPlugins={[remarkGfm]}
              >
                {summary}
              </ReactMarkdown>
            </Card>

            <p className="text-sm opacity-75 text-center">
              Note: This summary was generated by AI and may occasionally
              contain inaccuracies. Please review it carefully.
            </p>
          </>
        ) : (
          <div className="text-center text-zinc-500 dark:text-zinc-400 py-8">
            No summary available
          </div>
        )}
      </div>
    </div>
  );
};

export default SurveySummaryPage;
