import { Card } from "@/components/ui/card";
import api from "@/lib/axios.instance";
import { useQuery } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import rehypeRaw from "rehype-raw";
import rehypeHighlight from "rehype-highlight";
import { useAppSelector } from "@/hooks/useAppSelector";
import { Sparkles, RefreshCcw } from "lucide-react";
import { useState } from "react";
import { Button } from "@/components/ui/button";



 const SurveySummaryPage = () => {
  const { surveyId } = useParams();
  const { accessToken } = useAppSelector(state => state.user);
  const [isAuthentic, setIsAuthentic] = useState<boolean | null>(null);
  
  const { data: summary, isPending: isLoading, refetch } = useQuery({
    queryFn: async () => {
      const res = await api.get(`/api/assistant/summary/${surveyId}`, {
        params: {
            isAuthentic: JSON.stringify(isAuthentic)
        }
      });
      return res.data.summary;
    },
    queryKey: ["summary", surveyId, isAuthentic],
    enabled: !!accessToken && !!surveyId
  });

  const authenticityOptions = [
    { label: "All", value: null },
    { label: "Authentic", value: true },
    { label: "Not Authentic", value: false },
  ];

  return (
    <div className="max-w-5xl mx-auto py-10 px-4 space-y-6">
        <div className="bg-white dark:bg-zinc-900 rounded-xl border border-blue-50 dark:border-zinc-800 shadow p-6">
          <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
            <div>
              <h3 className="text-lg font-semibold text-blue-700 dark:text-blue-300">
                Authenticity Filter
              </h3>
              <p className="text-sm text-zinc-600 dark:text-zinc-400 mt-1">
                Filter responses by authenticity before generating summary
              </p>
            </div>

            <div className="flex items-center gap-2">
              <div className="flex bg-zinc-100 dark:bg-zinc-800 rounded-lg overflow-hidden shadow-md">
                {authenticityOptions.map((opt) => (
                  <button
                    key={String(opt.value)}
                    onClick={() => setIsAuthentic(opt.value)}
                    className={`px-4 py-2 text-sm font-medium transition-all ${
                      isAuthentic === opt.value
                        ? "bg-blue-600 text-white"
                        : "text-zinc-700 dark:text-zinc-300 hover:bg-zinc-200 dark:hover:bg-zinc-700"
                    }`}
                  >
                    {opt.label}
                  </button>
                ))}
              </div>
              
              <Button
                onClick={() => refetch()}
                disabled={isLoading}
                variant="outline"
                size="sm"
                className="flex items-center gap-2"
              >
                <RefreshCcw size={16} />
                Generate Again
              </Button>
            </div>
          </div>
        </div>

      <div className="bg-white dark:bg-zinc-900 rounded-xl border border-blue-50 dark:border-zinc-800 shadow p-6 space-y-6">
        {isLoading ? (
          <div className="w-full h-96 flex justify-center items-center">
            <div className="flex gap-3 items-center text-blue-600 dark:text-blue-400">
              <Sparkles size={24} className="animate-spin" />
              <span className="text-lg font-medium">Generating summary...</span>
            </div>
          </div>
        ) : summary ? (
          <>
            <div className="flex flex-col justify-center items-center gap-1 pb-4 border-b border-zinc-200 dark:border-zinc-800">
              <div className="flex justify-center items-center gap-2">
                <Sparkles size={20} className="text-blue-600 dark:text-blue-400" />
                <h2 className="text-2xl font-semibold text-zinc-900 dark:text-neutral-100">
                  AI Summary
                </h2>
              </div>
              <p className="text-sm text-zinc-500 dark:text-zinc-400">
                Model: openai/gpt-oss-120b
              </p>
            </div>

            <Card className="overflow-x-auto px-4 prose max-w-none dark:text-neutral-100 text-zinc-900 dark:bg-zinc-900 rounded-lg">
              <ReactMarkdown
                rehypePlugins={[rehypeRaw, rehypeHighlight]}
                remarkPlugins={[remarkGfm]}
              >
                {summary}
              </ReactMarkdown>
            </Card>

            <p className="text-sm opacity-50">
              Note: This summary was generated by AI and may occasionally contain inaccuracies. Please review it carefully.
            </p>
          </>
        ) : (
          <div className="text-center text-zinc-500 dark:text-zinc-400 py-8">
            No summary available
          </div>
        )}
      </div>
    </div>
  );
};


export default SurveySummaryPage;